### ISSUE TITLE
按照安装手册操作，好像执行的时候遇到报错，麻烦帮忙看看，谢谢。

### ISSUE THREAD

**Issue by macaty** [avyou/CDN_dig#2]
![image](https://user-images.githubusercontent.com/16797633/65129269-86b67a00-da2d-11e9-8cee-d42bfad2bab4.png)

[root@a5a78a98de29 CDN_dig]# cdig --help
Traceback (most recent call last):
  File "/usr/bin/cdig", line 11, in <module>
    load_entry_point('CDN-dig==1.0', 'console_scripts', 'cdig')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/cdig.py", line 13, in <module>
    import requests, re
ImportError: No module named requests

**Comment by macaty** [comment]
搞定了，
[root@a5a78a98de29 CDN_dig]# pip install requests

**Comment by macaty** [comment]
![image](https://user-images.githubusercontent.com/16797633/65132304-5671da00-da33-11e9-8063-2f228e112ed6.png)

Traceback (most recent call last):
  File "/usr/bin/cdig", line 11, in <module>
    load_entry_point('CDN-dig==1.0', 'console_scripts', 'cdig')()
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/cdig.py", line 530, in main
    output_tables(domain,edns,client_ip,area)
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/cdig.py", line 409, in output_tables
    getline(dns_parse_data_list,isp_ip_list,domain,edns,1,0)
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/cdig.py", line 320, in getline
    client_ip_area,nodeip_area = query_area(client_ip,node_ip,query_ip_show)
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/cdig.py", line 207, in query_area
    client_ip_area = ip_api(client_ip,default_api)
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/cdig.py", line 107, in wrapper
    area = func(*args,**kwargs)
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/cdig.py", line 191, in ip_api
    query_ip = QueryIP(api_dict,ip,api)
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/models/queryIP.py", line 24, in __init__
    self.selectAPI()
  File "/usr/lib/python2.7/site-packages/CDN_dig-1.0-py2.7.egg/cdn_dig/models/queryIP.py", line 174, in selectAPI
    self.api_dict_area[self.api] = self.area
AttributeError: 'QueryIP' object has no attribute 'area'
出现了新的报错
